WIP #165 Autenticação de usuário
Eccoar/boilerplate-backend pull request #5
Opened 2021-05-01 02:33 UTC by Arthur-Matos

Neste pull request se realizou:

- Rotas para autenticação e login de Usuário

2021-05-01 16:03 UTC, MatheusBlanco requested changes
Os testes estão retornando um unhandledPromiseRejection nos testes de error Handler. 

![image](https://user-images.githubusercontent.com/37380789/116787943-6d850480-aa7d-11eb-9ab3-afa80e4100be.png)

2021-05-01 16:03 UTC, MatheusBlanco commented on test/UserService.test.ts
> +	test('should return User id getting by email', async () => {
Eu sei que fizeram testes aqui, mas o coverage está falando que tem uma função não testada do signin. Podem dar uma olhada?
![image](https://user-images.githubusercontent.com/37380789/116787989-a624de00-aa7d-11eb-99af-a884f723f3ca.png)

2021-05-01 18:30 UTC, Arthur-Matos commented on test/UserService.test.ts
> +	test('should return User id getting by email', async () => {
É essa a função q ta dando B.O no teste

2021-05-01 18:32 UTC, MatheusBlanco commented on test/UserService.test.ts
> +	test('should return User id getting by email', async () => {
Ah é. Esqueci, sorry. Vai dar pra resolver?

2021-05-01 18:37 UTC, Arthur-Matos commented on test/UserService.test.ts
> +	test('should return User id getting by email', async () => {
tentarei...

2021-05-04 17:47 UTC, MatheusBlanco approved these changes

2021-05-07 03:52 UTC, devsalula requested changes
Eu estou sentindo falta de um logout ein. Por que vocês não implementaram?
O firebase tem na documentação deles um logOut que era para utilizar:
`firebase.auth().signOut().then(()`
https://firebase.google.com/docs/auth/web/password-auth?hl=pt-br
E não esqueçam de testar 😃

2021-05-07 03:52 UTC, devsalula commented on src/controllers/ControllerUser.ts
> +			return res.status(200).json({ token: jwt, userId: id });
O retorno desse userId é realmente necessário? Tendo em vista que no nosso jwt ele já possui as informações do usuário, incluindo o próprio id dele?

2021-05-07 03:52 UTC, devsalula commented on src/services/UserService.ts
> +			throw new BadRequest(error);
Ele vai retornar `BadRequest 400` até para quando o usuário errar a própria senha?
Eu quero pedir para ele cair no Unauthorized 401, para quando ele errar a própria senha. Eu imagino que o firebase informa que a senha está errada, é só verificar a mensagem de erro: https://firebase.google.com/docs/auth/admin/errors

2021-05-07 03:52 UTC, devsalula commented on src/services/UserService.ts
> +			throw new Unauthorized('Access denied');
Eu imagino que ele retorne esse erro, quando o JWT é inválido certo?
Para erros de autorização o status correto a se retornar é 403 com o erro de `Forbidden`. Por favor, criem esse erro lá no handler.  https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/403

2021-05-07 15:02 UTC, Arthur-Matos commented on src/controllers/ControllerUser.ts
> +			return res.status(200).json({ token: jwt, userId: id });
O Brian ta utilizando pra salvar o User Id no Local Storage a partir do login, a gente ta enviando para n ter que fazer 2 requisições.

2021-05-07 15:22 UTC, devsalula commented on src/controllers/ControllerUser.ts
> +			return res.status(200).json({ token: jwt, userId: id });
Mas então, vcs não precisam fazer uma segunda request. O JWT já carrega todas as informações do usuário, incluindo esse userId, sacou?
Daí vcs só removem esse retorno do userId daqui e utilizem uma lib chamada [jwt-decode](https://github.com/auth0/jwt-decode) para decodificar o jwt que o front recebe e pegar as informações do usuário.

2021-05-07 15:28 UTC, Arthur-Matos commented on src/controllers/ControllerUser.ts
> +			return res.status(200).json({ token: jwt, userId: id });
Blz, falei com o brian aqui. Ele vai tentar alterar no front.

2021-05-08 15:41 UTC, devsalula requested changes

2021-05-08 15:41 UTC, devsalula commented on test/controller.test.ts
> +import { NotFound, Unauthorized } from '@utils/ErrorHandler';
Não está sendo utilizado, retira por gentileza.

2021-05-08 15:41 UTC, devsalula commented on src/controllers/ControllerUser.ts
>  				adress: req.body.adress,
Colocar o nome correto de `address`

2021-05-08 15:41 UTC, devsalula commented on src/routes.ts
> +	'/api/authorization',
Acho que isso aqui pode ser um GET, pode não?

2021-05-08 15:41 UTC, devsalula commented on src/routes.ts
> +	'/api/authorization',
E passar o JWT como um header da request

2021-05-08 17:51 UTC, devsalula approved these changes

2021-05-08 17:51 UTC, merged