186 pipeline user
Eccoar/boilerplate-backend pull request #6
Opened 2021-05-01 21:31 UTC by guilhesme23

## Conteúdo

Adiciona gitlabci e helm charts ao projeto

2021-05-02 12:46 UTC, MatheusBlanco approved these changes

2021-05-03 17:49 UTC, devsalula commented
@Phe0 arranca o commit 6fbcd61 com squash, que eu aceito.

2021-05-03 17:50 UTC, devsalula requested changes
@Phe0 arranca o commit 6fbcd61 com squash, que eu aceito.

2021-05-03 18:16 UTC, devsalula approved these changes

2021-05-03 18:16 UTC, merged